### ISSUE TITLE
Flipped orientation in tracker protocol after switching sides

### ISSUE THREAD

**Issue by andre-ryll** [robotics-erlangen/autoref#4]
I reviewed the 2022 final gamelog [download](https://download.tigers-mannheim.de/gamelogs/2022/div-a/2022-07-16_11-34_TIGERs_Mannheim-vs-ER-Force.log.gz).

I noticed that the robot orientations are flipped by 180° in the second half. In this game the sides where switched for the second half.
Robots are mostly looking away from the ball, which seems obviously wrong.

**Comment by paul1999** [comment]
I remember this to be an issue at the RoboCup.

Michel said he will look into it, he is currently doing another task though.
